import { ToolProfile } from './types';

export const TOOL_PROFILES: ToolProfile[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    vendor: 'Anthropic',
    description: 'AI coding assistant with agentic capabilities — autonomous multi-step coding, debugging, refactoring, and architecture analysis across the full SDLC.',
    url: 'https://claude.ai',
    costPerSeatMonthly: 100,
    fixedMonthlyCost: 0,
    phaseApplicability: {
      Discovery: 0.6,
      Design: 0.7,
      Spec: 0.8,
      Dev: 1.0,
      QA: 0.8,
      'Release & Ops': 0.5,
    },
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    vendor: 'GitHub / Microsoft',
    description: 'AI pair programmer integrated into IDEs — inline code suggestions, chat, and code completion focused primarily on the development phase.',
    url: 'https://github.com/features/copilot',
    costPerSeatMonthly: 19,
    fixedMonthlyCost: 0,
    phaseApplicability: {
      Discovery: 0.1,
      Design: 0.2,
      Spec: 0.3,
      Dev: 1.0,
      QA: 0.5,
      'Release & Ops': 0.3,
    },
  },
  {
    id: 'cursor',
    name: 'Cursor',
    vendor: 'Anysphere',
    description: 'AI-native code editor with deep codebase understanding — intelligent code generation, refactoring, and multi-file editing capabilities.',
    url: 'https://cursor.com',
    costPerSeatMonthly: 20,
    fixedMonthlyCost: 0,
    phaseApplicability: {
      Discovery: 0.2,
      Design: 0.3,
      Spec: 0.4,
      Dev: 1.0,
      QA: 0.6,
      'Release & Ops': 0.3,
    },
  },
  {
    id: 'sap-joule',
    name: 'SAP Joule',
    vendor: 'SAP',
    description: 'SAP\'s AI copilot for business processes — assists with SAP configuration, ABAP development, business process automation, and operational analytics.',
    url: 'https://www.sap.com/products/artificial-intelligence/ai-copilot.html',
    costPerSeatMonthly: 30,
    fixedMonthlyCost: 0,
    phaseApplicability: {
      Discovery: 0.5,
      Design: 0.6,
      Spec: 0.5,
      Dev: 0.7,
      QA: 0.4,
      'Release & Ops': 0.6,
    },
  },
  {
    id: 'chatgpt-pro',
    name: 'ChatGPT Pro',
    vendor: 'OpenAI',
    description: 'General-purpose AI assistant with advanced reasoning (o1, GPT-4o) — research, analysis, document drafting, brainstorming, and code review. Broad SDLC coverage but not IDE-integrated.',
    url: 'https://openai.com/chatgpt/pricing/',
    costPerSeatMonthly: 200,
    fixedMonthlyCost: 0,
    phaseApplicability: {
      Discovery: 0.7,
      Design: 0.6,
      Spec: 0.7,
      Dev: 0.5,
      QA: 0.4,
      'Release & Ops': 0.3,
    },
  },
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    vendor: 'OpenAI',
    description: 'Cloud-based agentic coding assistant — runs autonomously in a sandboxed environment to write code, fix bugs, and run tests. Available via ChatGPT Team/Enterprise.',
    url: 'https://openai.com/index/introducing-codex/',
    costPerSeatMonthly: 25,
    fixedMonthlyCost: 0,
    phaseApplicability: {
      Discovery: 0.3,
      Design: 0.3,
      Spec: 0.4,
      Dev: 0.9,
      QA: 0.7,
      'Release & Ops': 0.3,
    },
  },
  {
    id: 'generic',
    name: 'Generic AI Tool',
    vendor: 'Various',
    description: 'A generic AI coding assistant profile representing an average tool with moderate capabilities across all SDLC phases. Use this as a baseline comparison.',
    url: '',
    costPerSeatMonthly: 20,
    fixedMonthlyCost: 0,
    phaseApplicability: {
      Discovery: 0.3,
      Design: 0.3,
      Spec: 0.4,
      Dev: 0.8,
      QA: 0.5,
      'Release & Ops': 0.3,
    },
  },
];
