import { ToolProfile } from './types';

export const TOOL_PROFILES: ToolProfile[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    vendor: 'Anthropic',
    description: 'AI coding assistant with agentic capabilities — autonomous multi-step coding, debugging, refactoring, and architecture analysis across the full SDLC. MCP integration, sub-agents, multi-surface (CLI, VS Code, JetBrains, Desktop).',
    url: 'https://claude.ai',
    costPerSeatMonthly: 100,
    fixedMonthlyCost: 0,
    rateLimitScore: 4,
    phaseApplicability: {
      Discovery: 0.65,
      Design: 0.75,
      Spec: 0.8,
      Dev: 1.0,
      QA: 0.85,
      'Release & Ops': 0.55,
    },
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    vendor: 'GitHub / Microsoft',
    description: 'AI pair programmer with agent mode, coding agent, and agentic code review — inline suggestions, chat, multi-file editing, and autonomous PR creation across the SDLC.',
    url: 'https://github.com/features/copilot',
    costPerSeatMonthly: 19,
    fixedMonthlyCost: 0,
    rateLimitScore: 2,
    phaseApplicability: {
      Discovery: 0.2,
      Design: 0.3,
      Spec: 0.4,
      Dev: 0.8,
      QA: 0.6,
      'Release & Ops': 0.4,
    },
  },
  {
    id: 'cursor',
    name: 'Cursor',
    vendor: 'Anysphere',
    description: 'AI-native code editor (SOC 2 Type II certified) with deep codebase understanding — intelligent code generation, refactoring, multi-file editing, and agent mode for autonomous coding tasks.',
    url: 'https://cursor.com',
    costPerSeatMonthly: 20,
    fixedMonthlyCost: 0,
    rateLimitScore: 2,
    phaseApplicability: {
      Discovery: 0.2,
      Design: 0.3,
      Spec: 0.4,
      Dev: 0.85,
      QA: 0.6,
      'Release & Ops': 0.3,
    },
  },
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    vendor: 'Google',
    description: 'Agent-first AI IDE built on VS Code — multi-agent orchestration, spec-driven development, browser sub-agent for visual verification, and verifiable artifacts. Supports Gemini 3, Claude, and OpenAI models.',
    url: 'https://antigravity.google',
    costPerSeatMonthly: 20,
    fixedMonthlyCost: 0,
    rateLimitScore: 2,
    phaseApplicability: {
      Discovery: 0.4,
      Design: 0.5,
      Spec: 0.7,
      Dev: 0.9,
      QA: 0.8,
      'Release & Ops': 0.4,
    },
  },
  {
    id: 'chatgpt-pro',
    name: 'ChatGPT Team',
    vendor: 'OpenAI',
    description: 'General-purpose AI assistant with advanced reasoning (o3, GPT-4.1) — research, analysis, document drafting, brainstorming, and code review. Shared workspace with admin controls. Broad SDLC coverage but not IDE-integrated.',
    url: 'https://openai.com/chatgpt/pricing/',
    costPerSeatMonthly: 25,
    fixedMonthlyCost: 0,
    rateLimitScore: null,
    phaseApplicability: {
      Discovery: 0.7,
      Design: 0.6,
      Spec: 0.7,
      Dev: 0.5,
      QA: 0.4,
      'Release & Ops': 0.3,
    },
  },
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    vendor: 'OpenAI',
    description: 'Cloud-based agentic coding assistant — runs autonomously in a sandboxed environment to write code, fix bugs, and run tests. Available via ChatGPT Business/Enterprise.',
    url: 'https://openai.com/index/introducing-codex/',
    costPerSeatMonthly: 30,
    fixedMonthlyCost: 0,
    rateLimitScore: 3,
    phaseApplicability: {
      Discovery: 0.3,
      Design: 0.3,
      Spec: 0.4,
      Dev: 0.9,
      QA: 0.75,
      'Release & Ops': 0.35,
    },
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    vendor: 'Cognition AI',
    description: 'AI-powered code editor with Cascade flow-based coding — intelligent autocomplete, multi-file editing, agentic coding, and Devin integration. SOC 2 Type II and FedRAMP High certified.',
    url: 'https://windsurf.com',
    costPerSeatMonthly: 15,
    fixedMonthlyCost: 0,
    rateLimitScore: null,
    phaseApplicability: {
      Discovery: 0.15,
      Design: 0.25,
      Spec: 0.35,
      Dev: 0.95,
      QA: 0.55,
      'Release & Ops': 0.25,
    },
  },
  {
    id: 'ms-copilot',
    name: 'MS Copilot',
    vendor: 'Microsoft',
    description: 'Microsoft 365 AI copilot for business productivity — assists with Word, Excel, Teams, PowerPoint, and Graph-connected workflows. Enterprise-grade with broad M365 integration.',
    url: 'https://www.microsoft.com/en-us/microsoft-365/copilot',
    costPerSeatMonthly: 30,
    fixedMonthlyCost: 0,
    rateLimitScore: null,
    phaseApplicability: {
      Discovery: 0.6,
      Design: 0.5,
      Spec: 0.7,
      Dev: 0.2,
      QA: 0.3,
      'Release & Ops': 0.4,
    },
  },
  {
    id: 'claude-cowork',
    name: 'Claude Cowork',
    vendor: 'Anthropic',
    description: 'Anthropic agentic tool for knowledge workers — document analysis, research, writing, Google Drive/Gmail integration, and team collaboration. "Claude Code for the rest of your work."',
    url: 'https://www.anthropic.com',
    costPerSeatMonthly: 25,
    fixedMonthlyCost: 0,
    rateLimitScore: null,
    phaseApplicability: {
      Discovery: 0.7,
      Design: 0.6,
      Spec: 0.7,
      Dev: 0.3,
      QA: 0.3,
      'Release & Ops': 0.3,
    },
  },
  {
    id: 'sap-joule',
    name: 'SAP Joule',
    vendor: 'SAP',
    description: 'SAP\'s AI copilot for business processes — assists with SAP configuration, ABAP development, business process automation, and operational analytics.',
    url: 'https://www.sap.com/products/artificial-intelligence/ai-copilot.html',
    costPerSeatMonthly: 30,
    fixedMonthlyCost: 0,
    rateLimitScore: null,
    phaseApplicability: {
      Discovery: 0.5,
      Design: 0.6,
      Spec: 0.5,
      Dev: 0.7,
      QA: 0.4,
      'Release & Ops': 0.6,
    },
  },
  {
    id: 'generic',
    name: 'Generic AI Tool',
    vendor: 'Various',
    description: 'A generic AI coding assistant profile representing an average tool with moderate capabilities across all SDLC phases. Use this as a baseline comparison.',
    url: '',
    costPerSeatMonthly: 20,
    fixedMonthlyCost: 0,
    rateLimitScore: null,
    phaseApplicability: {
      Discovery: 0.3,
      Design: 0.3,
      Spec: 0.4,
      Dev: 0.8,
      QA: 0.5,
      'Release & Ops': 0.3,
    },
  },
];
